spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/springcloud_sell?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
  rabbitmq:
    host: 192.168.7.80
    port: 5672
    username: guest
    password: guest
zuul:
  #全部服务忽略敏感头 （可以设置cookie）
  sensitive-headers: 
  routes:
    myProduct:
      path: /myProduct/**
      serviceId: product
  host:
    connect-timeout-millis: 15000 #HTTP连接超时要比Hystrix的大
    socket-timeout-millis: 60000   #socket超时
  #ignored-patterns:
    #- /**/product/**       #过滤排除某些路由
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
 #对外暴露接口，可以查看所有的接口映射 http://localhost:9000/actuator/routes
management:
  endpoints:
    web:
      exposure:
        include: "*" 
env:
  dev
