spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/springcloud_sell?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
  jpa:
    show-sql: true
  # 配置Swagger相关信息
  instance:
    prefer-ip-address: true
    instanceId: ${spring.cloud.client.ipAddress}:${server.port}
    status-page-url: http://${spring.cloud.client.ipAddress}:${server.port}/swagger-ui.html
    # ${server.port}为该服务的端口号
env:
  dev
